version: "3.3"

services:
    wordpress:
        image: wordpress:latest
        container_name: wordpress_portfolio
        restart: always
        ports:
            - "8080:80"
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress_password
            WORDPRESS_DB_NAME: wordpress_db
        volumes:
            - ./wordpress:/var/www/html

    db:
        image: mysql:5.7
        container_name: db_portfolio
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: wordpress_db
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress_password
        volumes:
            - ./mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root_password

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./wordpress:/var/www/html

volumes:
    db_data:
